# Generated by Django 4.2.5 on 2023-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("birthdate", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=8
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="random@email.com", max_length=254),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSC", "Computer Science"),
                            ("SEN", "Software Engineering"),
                            ("IFS", "Information Systems"),
                            ("CYS", "Cyber Security"),
                            ("IFT", "Information Technology"),
                        ],
                        max_length=3,
                    ),
                ),
                ("state_of_origin", models.CharField(default="Lagos", max_length=20)),
                ("courses", models.ManyToManyField(blank=True, to="curriculum.course")),
            ],
        ),
    ]
