# Generated by Django 4.2.5 on 2023-10-02 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("curriculum", "0001_initial"),
        ("profiles", "0002_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="level",
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("birthdate", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=8
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="random@email.com", max_length=254),
                ),
                ("state_of_origin", models.CharField(default="Lagos", max_length=20)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("CSC", "Computer Science"),
                            ("SEN", "Software Engineering"),
                            ("IFS", "Information Systems"),
                            ("CYS", "Cyber Security"),
                            ("IFT", "Information Technology"),
                        ],
                        max_length=3,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                ("lecturer_id", models.CharField(default="lecture155", max_length=256)),
                ("date_of_hire", models.DateTimeField()),
                ("teaching_experience", models.IntegerField()),
                ("courses_taught", models.ManyToManyField(to="curriculum.course")),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
