# Generated by Django 4.2.5 on 2023-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_lecturer_lecturer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture581", max_length=256),
        ),
    ]
