# Generated by Django 4.2.5 on 2023-10-06 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_lecturer_profile_picture_student_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="birthdate",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 6, 9, 48, 14, 680731, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture265", max_length=256),
        ),
        migrations.AlterField(
            model_name="student",
            name="birthdate",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 10, 6, 9, 48, 14, 680731, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.IntegerField(default=100),
        ),
    ]
