# Generated by Django 4.2.5 on 2023-10-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_alter_lecturer_lecturer_id_alter_lecturer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture752", max_length=256),
        ),
    ]
