# Generated by Django 4.2.5 on 2023-10-17 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0012_alter_lecturer_lecturer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="date_of_hire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 17, 15, 6, 15, 218972, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture365", max_length=256),
        ),
    ]
