# Generated by Django 4.2.5 on 2023-10-17 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_department"),
        ("profiles", "0013_alter_lecturer_date_of_hire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="courses_taught",
            field=models.ManyToManyField(blank=True, null=True, to="curriculum.course"),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="date_of_hire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 17, 15, 9, 22, 246894, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture800", max_length=256),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="teaching_experience",
            field=models.IntegerField(default=4),
        ),
    ]
