# Generated by Django 4.2.5 on 2023-10-17 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_department"),
        ("profiles", "0015_alter_lecturer_date_of_hire_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="courses_taught",
            field=models.ManyToManyField(blank=True, to="curriculum.course"),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="date_of_hire",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture424", max_length=256),
        ),
    ]
