# Generated by Django 4.2.5 on 2023-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_alter_lecturer_courses_taught_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture375", max_length=256),
        ),
    ]
