# Generated by Django 4.2.5 on 2023-10-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        (
            "profiles",
            "0021_remove_lecturer_department_remove_student_department_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture463", max_length=256),
        ),
    ]
