# Generated by Django 4.2.5 on 2023-10-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_lecturer_department_student_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture924", max_length=256),
        ),
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[
                    ("100", "100 Level"),
                    ("200", "200 Level"),
                    ("300", "300 Level"),
                    ("400", "400 Level"),
                    ("500", "500 Level"),
                ],
                default="500",
                max_length=3,
            ),
        ),
    ]
