# Generated by Django 4.2.5 on 2023-10-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_alter_lecturer_lecturer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="email",
            field=models.EmailField(
                default="random@email.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture200", max_length=256),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                default="random@email.com", max_length=254, unique=True
            ),
        ),
    ]
