# Generated by Django 4.2.5 on 2023-10-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_alter_lecturer_email_alter_lecturer_lecturer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture156", max_length=256),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
