# Generated by Django 4.2.5 on 2023-10-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0027_alter_lecturer_email_alter_lecturer_lecturer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecturer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="lecturer_id",
            field=models.CharField(default="lecture367", max_length=256),
        ),
    ]
