# Generated by Django 4.2.5 on 2023-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("S", "Student"), ("L", "Lecturer")], default="S", max_length=2
            ),
            preserve_default=False,
        ),
    ]
