# Generated by Django 4.2.5 on 2023-10-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_account_type"),
        ("accounts", "0009_alter_studentprofile_user"),
    ]

    operations = []
