# Generated by Django 4.2.5 on 2023-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_merge_20231020_1844"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("ADMIN", "Admin"),
                ],
                max_length=8,
            ),
        ),
    ]
