# Generated by Django 4.2.5 on 2023-10-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_account_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="teacherprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="Mike", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Obas", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[("S", "Student"), ("L", "Lecturer")], default="S", max_length=1
            ),
        ),
        migrations.DeleteModel(
            name="StudentProfile",
        ),
        migrations.DeleteModel(
            name="TeacherProfile",
        ),
    ]
