# Generated by Django 4.2.5 on 2023-10-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0006_alter_lecturer_birthdate_alter_lecturer_lecturer_id_and_more",
        ),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=256)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "head_of_department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="dept_in_charge_of",
                        to="profiles.lecturer",
                    ),
                ),
            ],
        ),
    ]
