# Generated by Django 4.2.5 on 2023-10-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_department"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Department",
        ),
    ]
