# Generated by Django 4.2.5 on 2023-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="comment",
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
