# Generated by Django 4.2.5 on 2023-10-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_studentattendance_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentattendance",
            options={
                "verbose_name": "StudentAttendance item",
                "verbose_name_plural": "StudentAttendance items",
            },
        ),
    ]
